### ISSUE TITLE
Set archive bit on folder

### ISSUE THREAD

**Issue by Saulotas** [Johnmaras/splitNSP#1]
Can we use
subprocess.call(["ls", "-l"])
https://docs.python.org/2/library/subprocess.html

To initiate this command:
attrib +a [folder]
https://www.lifewire.com/attrib-command-2625802

To the created folder?

**Comment by Johnmaras** [comment]
Done since b03a3815e986ba8fbd9dcf898568b6275e1b8ec1 commit
